import I18n from 'react-native-i18n';

I18n.fallbacks = true;

/**
 * 国际化字符的翻译列表
 */
I18n.translations = {
  en: {
    'no openType':'Unknown',
    'call open':'Call open',
    'password open':'Password open',
    'face open':'Face open',
    'app open':'App open',
    'card open':'Card open',
    'no room':'Please apply for a house first',
    'info manager':'Info Manager',
    'wisdom group':'Wisdom Group',
    'housekeeper': 'Housekeeper',
    'community forum':'Community Forum',
    'business':'Business',
    'personal center':'Personal Center',
    'all locks':'All Locks',
    'visitor access':'Visitor Access',
    'no notice':'There is no notice info',
    'account':'please input account',
    'password':'please input password',
    'sign up':'sign up',
    'register':'register',
    'no account':'cannot find account',
    'password wrong':'wrong password',
    'today':'today',
    'yesterday':'yesterday',
    'now':'now',
    'day':'day',
    'hour':'hour',
    'minute':'minute',
    'meter':'meter',
    'kilometre':'kilometre',
    'new trouble':'new trouble',
    'accept':'accept',
    'arranged':'arranged',
    'done':'done',
    'new advice':'new advice',
    'adopt':'adopt',
    'deleted':'deleted',
    'high rise':'high rise',
    'multi storey':'multi storey',
    'townhouse':'townhouse',
    'villa':'villa',
    'shop':'shop',
    'office building':'office building',
    'owner':'owner',
    'family':'family',
    'tenant':'tenant',
    'paied':'paied',
    'canceled':'canceled',
    'to be confirmed':'to be confirmed',
    'confirmed':'confirmed',
    'to delete':'to delete',
    'square meter':'square meter',
    'tone':'tone',
    'kilowatt hour':'kilowatt hour',
    'car':'car',
    'yuan':'dollor',
    'unread':'unread',
    'read':'read',
    'no login':'you need login app',
    'no unit':'you have no unit',
    'switch unit success':'switch unit success',
    'application':'application',
    'unit type':'unit type',
    'unit area':'unit area',
    'unit members':'unit members',
    'unit cars':'unit cars',
    'add':'add',
    'delete':'delete',
    'edit':'edit',
    'system error':'system error',
    'cancel':'Cancel',
    'confirm':'Confirm',
    'ok':'OK',
    'delete member confirm':'are you sure you want to delete this member?',
    'delete car confirm':'are you sure you want to delete this car',
    'delete unit confirm':'are you sure you want to delete this unit',
    'car NO input':'please input the car NO',
    'car NO format':'Car NO just like C23944',
    'city':'city',
    'community':'community',
    'block':'block',
    'unit':'unit',
    'choose unit':'please choose your unit',
    'application info':'application info',
    'lock list':'remote lock list',
    'ble lock list':'ble lock list nearby',
    'name':'name',
    'mobile':'mobile',
    'identify':'identity card',
    'owner sence':'your application need the community manangement approvement',
    'other sence':'your application will send SMS to owner to approve',
    'user type':'please choose the user type',
    'owner mobile':'owner mobile',
    'verify code':'verify code',
    'send code':'send code',
    'send code limit':'SMS verify need wait 1 minute',
    'wait':'wait',
    'second':'second',
    'wrong mobile':'your phone NO is invalide',
    'wrong mobile len':'your phone NO need 11 digit',
    'must choose unit':'you must choose one unit',
    'duplicated unit':'you have this unit already',
    'must choose mobile':'must choose the mobile of owner',
    'must input code':'must input verify code',
    'application sent':'application has been sent',
    'wrong code':'wrong code',
    'duplicated application':'duplicated application',
    'incorrect ID card':'incorrect ID card',
    'repassword':'reinput password',
    'need account':'please input the account',
    'need password':'please input the password',
    'need realname':'please input the realname',
    'duplicated account':'duplicated account',
    'realname':'realname',
    'not same password':'two password are not same',
    'visitor attention':'you can create password for visitor and share',
    'create':'create',
    'input title':'please input the title (100 characters limit)',
    'input content':'please input the content (1000 characters limit)',
    'calling':'calling',
    'manage fee':'management fee',
    'pay now':'pay now',
    'see detail':'see detail',
    'unpaied bill':'unpaied bill',
    'total':'total',
    'fee name':'fee name',
    'fee rate':'fee rate',
    'quantity':'quantity',
    'amount':'amount',
    'change password':'change password',
    'logout':'logout',
    'about us':'about us',
    'help':'help',
    'question':'question',
    'logout confirm':'are you sure to logout?',
    'unknow user':'unknow user',
    'unknow mobile':'you are not logged in',
    'old password':'old password',
    'new password':'new password',
    'need old password':'please input the old password',
    'need new password':'please input the new password',
    'old password wrong':'the old password you inputed is wrong',
    'no access image':'no access image',
    'register success':'the accout register success',
    'to':'to',
    'no data':'no more data',
    'delete unit success':'delete unit success',
    'create topic':'create new topic',
    'save success':'saved successfully',
    'reply':'reply',
    'back exit':'press back again will exit',
    'send im success':'send im success',
    'send im failed':'send im failed','':'',
    'no rtc':'RTC Service is not ready',
    'choose image type':'choose image from',
    'take picture':'take a photo',
    'pick from lib':'pick from lib',
    'choose share type':'choose share type',
    'weixin':'weixin',
    'SMS':'SMS',
    'QQ':'QQ',
    'no network':'no network',
    'mobile registered already':'this mobile has been registered already',
    'rtc ready':'Rtc Service is ready',
    'more function':'more function',
    'more':'more',
    'lift switch':'lift control',
    'no lift':'you are not in a lift',
    'lift in':'you enter into the lift',
    'lift out':'you leave from the lift',
    'no community':'you have not join community',
    'no forum':'this community have no forum',
    'no shop category':'this community have no shop category',
    'loading':'in loading',
    'shop info':'shop info',
    'goods info':'goods info',
    'coupon info':'coupon info',
    'tel':'tel',
    'address':'address',
    'expire date':'expire date',
    'shop address':'shop address',
    'scan coupon':'please scan the qrcode to write off coupon',
    'promotion date':'promotion date',
    'used':'used',
    'overdue':'overdue',
    'choose owner mobile':'please choose owner mobile',
    'no device':'no indoor device',
    'family intercom':'family intercom',
    'on call failed':'call door machine failed',
    'on talk failed':'call family indoor failed',
    'lockOrUnlock':'lock or unlock',
    'lock':'lock',
    'unlock':'unlock',
    'lock car fail':'lock car fail',
    'unlock car fail':'unlock car fail',
    'used coupon':'used coupon',
    'invalid coupon':'invalid coupon',
    'can use':'can use ',
    'times':'times',
    'times limit':'times limit',
    'peroid limit':'peroid limit',
    'peroid limit in 7 days':'peroid limit in 7 days',
    'times limit large than 1':'times limit large than 1',
    'create unit member':'create unit member',
    'member name':'member name',
    'unit No':'unit No',
    'visitor password':'visitor password',
    'new ble lock':'find new ble lock',
    'time out':'time out',
    'cannot connect to BLE':'cannot connect to BLE device',
    'access invalid':'access invalid',
    'open ble lock success':'open ble lock success',
    'network error':'network error',
    'admin center':'admin center',
    'change account':'change account',
    'confirm change account':'are you sure to change the account?',

    'MapPane':'Map',
    'InputScreen':'Input Screen',
    'ImageGallery':'Image Gallery',
    'LoginScreen':'Login',
    'RegisterScreen':'Register',
    'UnitSwitchScreen':'Unit Switch',
    'UnitApplicationScreen':'Unit Application',
    'UnitScreen':'Unit List',
    'UnitDetailScreen':'Unit Detail',
    'UnitCarScreen':'Unit Car',
    'UnitCarHistoryScreen':'Car Entry History',
    'UnitCommunityScreen':'Choose Community',
    'UnitCityScreen':'Choose City',
    'UnitBlockScreen':'Choose Block',
    'UnitChooseScreen':'Choose Unit',
    'NoticeScreen':'Notice',
    'NoticeDetailScreen':'Notice Detail',
    'LockScreen':'Lock List',
    'VisitorAccessScreen':'Visitor Access',
    'LockHistoryScreen':'Lock Open History',
    'VisitorCreateScreen':'Visitor Access Create',
    'AdviceScreen':'Advice',
    'AdviceCreateScreen':'Advice Create',
    'AdviceDetailScreen':'Advice Detail',
    'TroubleScreen':'Trouble',
    'TroubleCreateScreen':'Trouble Create',
    'TroubleDetailScreen':'Trouble Detail',
    'ContactScreen':'Contact List',
    'BillScreen':'Bill Profile',
    'LiftControl':'Lift',
    'BillHistoryScreen':'Bill History',
    'BillDetailScreen':'Bill Detail',
    'ChangePasswordScreen':'Change Password',
    'ChangeAccountScreen':'Change Account',
    'HelpScreen':'Help',
    'AboutScreen':'About Us',
    'UserDetailScreen':'User Detail Info',
    'TopicDetailScreen':'Topic Detail',
    'TopicEditScreen':'Topic Edit',
    'ReplyEditScreen':'Reply Edit',
    'ReplyScreen':'Reply',
    'ShopDetailScreen':'Shop Detail',
    'ForumScreen':'Forum',
    'GoodsDetailScreen':'Goods Detail',
    'PromotionDetailScreen':'Promotion Detail',
    'CouponDetailScreen':'Coupon Detail',
    'CouponScreen':'My Coupon',
    'DeviceScreen':'Indoor Device List',
    'PhotoScreen':'My Photo',

    'Q0':'About Us',
    'Q0_A':'Shenzhen city node Technology Co., Ltd. focus on the wisdom of the community, is committed to creating a smart community life. The wisdom of the community is the companys operating platform for the whole platform of the whole community of intelligent community solutions. The top-level design based on mobile Internet, large data networking and three core technologies, is only able to Chinese intelligent security system hardware, smart and intelligent community property management of all media advertising and intelligent community life service platform and super intelligent housekeeper and a number of open platform is connected to the. We create a safer and more convenient way of life as a vision, the first in China through the mobile Internet technology and intelligent hardware combined model. To provide a new generation of intelligent vehicle management, intelligent access control, intelligent visitor management, intelligent video intercom management, intelligent elevator control hardware and Internet based mobile property system to implement seamless docking, provide a new intelligence community experience for community residents and property.',
    'Q1':'how to change the language for the APP',
    'Q1_A':'you need change the default language of the mobile phone in the setting pane, and then restart the APP'
  },
  zh: {
    'no openType':'未知',
    'call open':'呼叫开门',
    'password open':'密码开门',
    'face open':'人脸开门',
    'app open':'App 开门',
    'card open':'刷卡开门',
    'no room':'请先申请房屋',
    'info manager':'信息管理',
    'wisdom group':'智慧社区',
    'housekeeper': '物业管家',
    'community forum':'社区',
    'business':'周边商圈',
    'personal center':'个人中心',
    'all locks':'小区门禁',
    'visitor access':'访客通行',
    'no notice':'暂无通知公告信息',
    'account':'请输入登录账号',
    'password':'请输入密码',
    'sign up':'登录',
    'register':'注册',
    'no account':'账号不存在',
    'password wrong':'密码错误',
    'today':'今日',
    'yesterday':'昨日',
    'now':'立即',
    'day':'天',
    'hour':'小时',
    'minute':'分钟',
    'meter':'米',
    'kilometre':'公里',
    'new trouble':'新故障',
    'accept':'已受理',
    'arranged':'已派工',
    'done':'已完成',
    'new advice':'新建议',
    'adopt':'已采纳',
    'deleted':'已删除',
    'high rise':'高层',
    'multi storey':'多层',
    'townhouse':'联排',
    'villa':'别墅',
    'shop':'商铺',
    'office building':'写字楼',
    'owner':'业主',
    'family':'家属',
    'tenant':'租客',
    'paied':'已支付',
    'canceled':'已取消',
    'to be confirmed':'等待确认',
    'confirmed':'已确认',
    'to delete':'等待删除',
    'square meter':'平米',
    'tone':'吨',
    'kilowatt hour':'度',
    'car':'车',
    'yuan':'元',
    'unread':'未读',
    'read':'已读',
    'no login':'您是未登录状态',
    'no unit':'您还没有指定房屋',
    'switch unit success':'房屋切换成功',
    'application':'申请',
    'unit type':'房屋类型',
    'unit area':'房屋面积',
    'unit members':'相关人员',
    'unit cars':'相关车辆(按月缴纳停车费)',
    'add':'添加',
    'delete':'删除',
    'edit':'编辑',
    'system error':'系统错误',
    'cancel':'取消',
    'confirm':'确认',
    'ok':'确认',
    'delete member confirm':'您确认删除该房屋成员吗?',
    'delete car confirm':'您确认删除这个车辆吗?',
    'delete unit confirm':'您确认要删除该房屋吗？',
    'car NO input':'请输入车牌号',
    'car NO format':'车牌号类似 粤B45678',
    'city':'城市',
    'community':'小区',
    'block':'楼栋',
    'unit':'单元',
    'choose unit':'请选择您的房屋',
    'application info':'申请者信息',
    'lock list':'小区所有门禁，点击远程开门',
    'ble lock list':'周边蓝牙门禁，点击近距开门',
    'name':'姓名',
    'mobile':'手机',
    'identify':'身份证号',
    'owner sence':'您申请成为该房屋的业主，需要管理处审核',
    'other sence':'需要发送短信校验码给业主进行校验',
    'user type':'请选择用户类别',
    'owner mobile':'业主手机',
    'verify code':'校验码',
    'send code':'发送校验码',
    'send code limit':'重发验证码需等待1分钟',
    'wait':'等待',
    'second':'秒',
    'wrong mobile':'您的手机号不正确',
    'wrong mobile len':'您的手机号需要11位数字',
    'must choose unit':'您必须先选择房屋',
    'duplicated unit':'您已经是该房屋成员，不能重复添加',
    'must choose mobile':'请选择业主手机号，如果业主手机号列表为空则表示该房屋暂无业主',
    'must input code':'请输入发送给业主的验证码',
    'application sent':'您提交的申请已经发给管理处，请耐心等待',
    'wrong code':'您输入的验证码无效或已过期',
    'duplicated application':'您已经提交了申请，不能重复申请',
    'incorrect ID card':'输入正确的身份证号',
    'repassword':'再次输入密码',
    'need account':'请输入账户手机号码',
    'need password':'请输入密码',
    'need realname':'请输入姓名',
    'duplicated account':'您输入的手机号已经被注册',
    'realname':'姓名',
    'not same password':'两次输入的密码不一致',
    'visitor attention':'选择动态密码，点击转发给访客',
    'create':'新建',
    'input title':'请输入标题 (字数在100以内)',
    'input content':'请输入详细内容 (字数在1000以内)',
    'calling':'正在呼叫',
    'manage fee':'物业费用',
    'pay now':'立即支付',
    'see detail':'查看明细',
    'unpaied bill':'账单未支付',
    'total':'共',
    'fee name':'费用名称',
    'fee rate':'费率',
    'quantity':'计费数量',
    'amount':'合计',
    'change password':'修改密码',
    'logout':'退出登录',
    'about us':'关于我们',
    'help':'帮助',
    'question':'问题',
    'logout confirm':'您确定退出登录吗?',
    'unknow user':'未知用户',
    'unknow mobile':'您目前处于未登录状态',
    'old password':'原密码',
    'new password':'新密码',
    'need old password':'请输入原密码',
    'need new password':'请输入新密码',
    'old password wrong':'您输入的原密码不正确',
    'no access image':'没有访客图片',
    'register success':'账号注册成功',
    'to':'至',
    'no data':'没有新的数据',
    'delete unit success':'您已经退出该房屋',
    'create topic':'创建新话题',
    'save success':'保存成功',
    'reply':'回复',
    'back exit':'再按一次退出',
    'send im success':'指令发送成功',
    'send im failed':'指令发送失败',
    'no rtc':'对讲服务未启动好',
    'choose image type':'请选择图片来源',
    'take picture':'相机',
    'pick from lib':'图库',
    'choose share type':'选择分享方式',
    'weixin':'微信',
    'SMS':'短信',
    'QQ':'QQ',
    'no network':'网络连接失败',
    'mobile registered already':'该号码已经被注册了',
    'rtc ready':'可视对讲服务正常',
    'more function':'即将推出，尽情期待',
    'more':'更多',
    'lift switch':'乘坐电梯',
    'no lift':'您需要进入电梯后再进行楼层选择',
    'lift in':'您已进入电梯，请选择楼层',
    'lift out':'您已经离开电梯',
    'no community':'您还没有加入小区',
    'no forum':'当前小区社区论坛暂不开放',
    'no shop category':'当前小区周边商圈暂不开放',
    'loading':'正在加载中...',
    'shop info':'店铺',
    'goods info':'产品',
    'coupon info':'我的优惠券',
    'tel':'电话',
    'address':'地址',
    'expire date':'使用期限',
    'shop address':'店铺地址',
    'scan coupon':'请扫描二维码核销优惠券',
    'promotion date':'活动时间',
    'used':'已使用',
    'overdue':'已过期',
    'choose owner mobile':'请选择业主手机',
    'no device':'您没有安装室内机',
    'family intercom':'家庭对讲',
    'on call failed':'连接门禁机失败',
    'on talk failed':'呼叫室内机失败',
    'lockOrUnlock':'锁车及解锁',
    'lock':'锁车',
    'unlock':'解锁',
    'lock car fail':'锁车失败',
    'unlock car fail':'解除锁车失败',
    'used coupon':'优惠券已使用',
    'invalid coupon':'优惠券已失效',
    'can use':'使用次数',
    'times':'次',
    'times limit':'次数限制',
    'peroid limit':'时间限制',
    'peroid limit in 7 days':'结束时间必须在7天内',
    'times limit large than 1':'次数限制必须大于1次',
    'create unit member':'创建家庭成员',
    'member name':'成员名称',
    'unit No':'房屋编号',
    'visitor password':'访客密码',
    'new ble lock':'发现新的蓝牙门禁',
    'time out':'访问蓝牙设备超时',
    'cannot connect to BLE':'无法连接到蓝牙设备',
    'access invalid':'访问限制',
    'open ble lock success':'成功打开蓝牙门禁',
    'network error':'网络异常',
    'admin center':'管理中心',
    'change account':'修改登录账户',
    'confirm change account':'您确认要修改登录账户吗?',

    'InputScreen':'信息输入',
    'MapPane':'地图导航',
    'ImageGallery':'图片浏览',
    'LoginScreen':'系统登录',
    'RegisterScreen':'系统注册',
    'UnitSwitchScreen':'房屋选择',
    'UnitApplicationScreen':'房屋申请',
    'UnitScreen':'我的房屋',
    'UnitDetailScreen':'房屋详情',
    'UnitCarScreen':'我的车辆',
    'UnitCarHistoryScreen':'停车记录',
    'UnitCommunityScreen':'选择小区',
    'UnitCityScreen':'选择城市',
    'UnitBlockScreen':'选择楼栋',
    'UnitChooseScreen':'选择房屋',
    'NoticeScreen':'通知公告',
    'NoticeDetailScreen':'公告详情',
    'LockScreen':'小区门禁',
    'VisitorAccessScreen':'访客通行',
    'LockHistoryScreen':'开门记录',
    'VisitorCreateScreen':'创建访客密码',
    'AdviceScreen':'投诉建议',
    'AdviceCreateScreen':'创建投诉建议',
    'AdviceDetailScreen':'投诉建议详情',
    'TroubleScreen':'维修申报',
    'TroubleCreateScreen':'创建维修申报',
    'TroubleDetailScreen':'维修申报详情',
    'ContactScreen':'联系物业',
    'BillScreen':'物业缴费',
    'LiftControl':'电　梯',
    'BillHistoryScreen':'已支付账单',
    'BillDetailScreen':'账单详情',
    'ChangePasswordScreen':'修改密码',
    'ChangeAccountScreen':'修改登录账户',
    'HelpScreen':'帮助',
    'AboutScreen':'关于我们',
    'UserDetailScreen':'用户信息',
    'TopicDetailScreen':'话题详情',
    'TopicEditScreen':'话题编辑',
    'ReplyEditScreen':'话题回复',
    'ReplyScreen':'评论回复',
    'ShopDetailScreen':'店铺详情',
    'ForumScreen':'社区论坛',
    'GoodsDetailScreen':'商品详情',
    'PromotionDetailScreen':'促销活动',
    'CouponDetailScreen':'优惠券详情',
    'CouponScreen':'我的优惠券',
    'DeviceScreen':'室内机列表',
    'PhotoScreen':'我的相框',

    'Q0':'关于我们',
    'Q0_A':'深圳市结点科技有限公司聚焦智慧社区，致力于创造智慧社区生活。公司运营的智慧社区项目是全生态全平台智慧社区整体解决方案。其顶层设计基于移动互联网、物联网和大数据三大核心技术，是中国唯一能把智能安防硬件、智慧物业管理、智慧社区全媒体广告、智慧社区生活服务平台和超级智能管家等多个开放平台连接起来的系统。我们以创造更安全、更方便的生活方式为愿景，在国内首家通过移动互联技术与智能硬件相结合的模式。提供新一代智能车辆管理、智能门禁管理、智能访客管理、智能可视对讲管理、智能电梯控制等硬件设备和基于移动互联网的物业系统实行无缝对接，为社区居民及物业提供全新的智慧社区体验。',
    'Q1':'如何修改APP的语言？',
    'Q1_A':'我们的APP支持国际化操作，您只需要在手机的设置中，修改当前的国家及语言，重启APP后即可'
  },
  "zh-HK": {
    'no openType':'未知',
    'call open':'呼叫開門',
    'password open':'密碼開門',
    'face open':'人臉開門',
    'app open':'App 開門',
    'card open':'刷卡開門',
    'no room':'請先申請房屋',
    'info manager':'資訊管理',
    'wisdom group':'智慧社區',
    'housekeeper': '物業管家',
    'community forum':'社區',
    'business':'周邊商圈',
    'personal center':'個人中心',
    'all locks':'社區門禁',
    'visitor access':'訪客通行',
    'no notice':'暫無通知公告資訊',
    'account':'請輸入登入帳號',
    'password':'請輸入密碼',
    'sign up':'登入',
    'register':'注册',
    'no account':'帳號不存在',
    'password wrong':'密碼錯誤',
    'today':'今日',
    'yesterday':'昨日',
    'now':'即刻',
    'day':'天',
    'hour':'小時',
    'minute':'分鐘',
    'meter':'米',
    'kilometre':'公里',
    'new trouble':'新問題',
    'accept':'已受理',
    'arranged':'已派工',
    'done':'已完成',
    'new advice':'新建議',
    'adopt':'已採納',
    'deleted':'已删除',
    'high rise':'高層',
    'multi storey':'多層',
    'townhouse':'聯排',
    'villa':'别墅',
    'shop':'商鋪',
    'office building':'辦公樓',
    'owner':'業主',
    'family':'家屬',
    'tenant':'租客',
    'paied':'已支付',
    'canceled':'已取消',
    'to be confirmed':'等待確認',
    'confirmed':'已確認',
    'to delete':'等待删除',
    'square meter':'平米',
    'tone':'噸',
    'kilowatt hour':'度',
    'car':'車',
    'yuan':'元',
    'unread':'未讀',
    'read':'已讀',
    'no login':'您是未登錄狀態',
    'no unit':'您還沒有指定房屋',
    'switch unit success':'房屋切換成功',
    'application':'申請',
    'unit type':'房屋類型',
    'unit area':'房屋面積',
    'unit members':'相關人員',
    'unit cars':'相關車輛(按月繳納停車費)',
    'add':'添加',
    'delete':'删除',
    'edit':'編輯',
    'system error':'系統錯誤',
    'cancel':'取消',
    'confirm':'確定',
    'ok':'確定',
    'delete member confirm':'您確認删除該房屋成員嗎?',
    'delete car confirm':'您確認删除這個車輛嗎?',
    'delete unit confirm':'您確認要删除該房屋嗎？',
    'car NO input':'請輸入車牌號',
    'car NO format':'車牌號類似粵B45678',
    'city':'城市',
    'community':'社區',
    'block':'樓棟',
    'unit':'單元',
    'choose unit':'請選擇您的房屋',
    'application info':'申請者資訊',
    'lock list':'社區門禁清單',
    'ble lock list':'您周圍的藍牙門禁',
    'name':'姓名',
    'mobile':'手機',
    'identify':'身份證號',
    'owner sence':'您申請成為該房屋的業主，需要管理處稽核',
    'other sence':'需要發送短信校驗碼給業主進行校驗',
    'user type':'請選擇用戶類別',
    'owner mobile':'業主手機',
    'verify code':'校驗碼',
    'send code':'發送校驗碼',
    'send code limit':'重發驗證碼需等待1分鐘',
    'wait':'等待',
    'second':'秒',
    'wrong mobile':'您的手機號不正確',
    'wrong mobile len':'您的手機號需要11比特數位',
    'must choose unit':'您必須先選擇房屋',
    'duplicated unit':'您已經是該房屋成員，不能重複添加',
    'must choose mobile':'請選擇業主手機號，如果業主手機號清單為空則表示該房屋暫無業主',
    'must input code':'請輸入發送給業主的驗證碼',
    'application sent':'您提交的申請已經發給管理處，請耐心等待',
    'wrong code':'您輸入的驗證碼無效或已過期',
    'duplicated application':'您已經提交了申請，不能重複申請',
    'incorrect ID card':'輸入正確的身份證號',
    'repassword':'再次輸入密碼',
    'need account':'請輸入帳戶手機號碼',
    'need password':'請輸入密碼',
    'need realname':'請輸入姓名',
    'duplicated account':'您輸入的手機號已經被注册',
    'realname':'姓名',
    'not same password':'兩次輸入的密碼不一致',
    'visitor attention':'選擇動態密碼，點擊轉發給訪客',
    'create':'新建',
    'input title':'請輸入標題（字數在100以內）',
    'input content':'請輸入詳細內容（字數在1000以內）',
    'calling':'正在呼叫',
    'manage fee':'物業費用',
    'pay now':'立即支付',
    'see detail':'查看明細',
    'unpaied bill':'帳單未支付',
    'total':'共',
    'fee name':'費用名稱',
    'fee rate':'費率',
    'quantity':'計費數量',
    'amount':'合計',
    'change password':'修改密碼',
    'logout':'登出',
    'about us':'關於我們',
    'help':'幫助',
    'question':'問題',
    'logout confirm':'您確定登出嗎？',
    'unknow user':'未知用戶',
    'unknow mobile':'您目前處於未登錄狀態',
    'old password':'原密碼',
    'new password':'新密碼',
    'need old password':'請輸入原密碼',
    'need new password':'請輸入新密碼',
    'old password wrong':'您输入的原密码不正确',
    'no access image':'沒有訪客圖片',
    'register success':'帳號注册成功',
    'to':'至',
    'no data':'沒有新的數據',
    'delete unit success':'您已經退出該房屋',
    'create topic':'創建新話題',
    'save success':'保存成功',
    'reply':'回復',
    'back exit':'再按一次退出',
    'send im success':'指令發送成功',
    'send im failed':'指令發送失敗',
    'no rtc':'對講服務未啟動好',
    'choose image type':'請選擇圖片來源',
    'take picture':'相機',
    'pick from lib':'圖庫',
    'choose share type':'選擇分享管道',
    'weixin':'微信',
    'SMS':'簡訊',
    'QQ':'QQ',
    'no network':'網絡連接失敗',
    'mobile registered already':'該號碼已經被注册了',
    'rtc ready':'可視對講服務正常',
    'more function':'即將推出，盡情期待',
    'more':'更多',
    'lift switch':'乘坐電梯',
    'no lift':'您需要進入電梯後再進行樓層選擇',
    'lift in':'您已進入電梯，請選擇樓層',
    'lift out':'您已經離開電梯',
    'no community':'您還沒有加入社區',
    'no forum':'當前社區社區論壇暫不開放',
    'no shop category':'當前社區周邊商圈暫不開放',
    'loading':'正在加載中...',
    'shop info':'店鋪',
    'goods info':'產品',
    'coupon info':'我的優惠券',
    'tel':'電話',
    'address':'地址',
    'expire date':'使用期限',
    'shop address':'店鋪地址',
    'scan coupon':'請掃描二維碼核銷優惠券',
    'promotion date':'活動時間',
    'used':'已使用',
    'overdue':'已過期',
    'choose owner mobile':'請選擇業主手機',
    'no device':'您沒有安裝室內機',
    'family intercom':'家庭對講',
    'on call failed':'連接門禁機失敗',
    'on talk failed':'呼叫室內機失敗',
    'lockOrUnlock':'鎖車及解鎖',
    'lock':'鎖車',
    'unlock':'解鎖',
    'lock car fail':'鎖車失敗',
    'unlock car fail':'解除鎖車失敗',
    'used coupon':'優惠券已使用',
    'invalid coupon':'優惠券已失效',
    'can use':'使用次数',
    'times':'次',
    'times limit':'次數限制',
    'peroid limit':'時間限制',
    'peroid limit in 7 days':'結束時間必須在7天內',
    'times limit large than 1':'次數限制必須大於1次',
    'create unit member':'創建家庭成員',
    'member name':'成員名稱',
    'unit No':'房屋編號',
    'visitor password':'訪客密碼',
    'new ble lock':'發現新的藍牙門禁',
    'time out':'訪問藍牙設備超時',
    'cannot connect to BLE':'無法連接到藍牙設備',
    'access invalid':'訪問限制',
    'open ble lock success':'成功打開藍牙門禁',
    'network error':'網絡异常',
    'admin center':'管理中心',
    'change account':'修改登入帳戶',
    'confirm change account':'您確認要修改登入帳戶嗎?',

    'InputScreen':'資訊輸入',
    'MapPane':'地圖導航',
    'ImageGallery':'圖片瀏覽',
    'LoginScreen':'系統登入',
    'RegisterScreen':'系統注册',
    'UnitSwitchScreen':'房屋選擇',
    'UnitApplicationScreen':'房屋申請',
    'UnitScreen':'房屋清單',
    'UnitDetailScreen':'房屋詳情',
    'UnitCarScreen':'我的車輛',
    'UnitCarHistoryScreen':'停車記錄',
    'UnitCommunityScreen':'選擇社區',
    'UnitCityScreen':'選擇城市',
    'UnitBlockScreen':'選擇樓棟',
    'UnitChooseScreen':'選擇房屋',
    'NoticeScreen':'物業公告',
    'NoticeDetailScreen':'公告詳情',
    'LockScreen':'社區門禁',
    'VisitorAccessScreen':'訪客通行',
    'LockHistoryScreen':'開門記錄',
    'VisitorCreateScreen':'創建訪客密碼',
    'AdviceScreen':'投訴建議',
    'AdviceCreateScreen':'創建投訴建議',
    'AdviceDetailScreen':'投訴建議詳情',
    'TroubleScreen':'維修申報',
    'TroubleCreateScreen':'創建維修申報',
    'TroubleDetailScreen':'維修申報詳情',
    'ContactScreen':'聯系物業',
    'BillScreen':'物業繳費',
    'LiftControl':'電　梯',
    'BillHistoryScreen':'已支付帳單',
    'BillDetailScreen':'帳單詳情',
    'ChangePasswordScreen':'修改密碼',
    'ChangeAccountScreen':'修改登入帳戶',
    'HelpScreen':'幫助',
    'AboutScreen':'關於我們',
    'UserDetailScreen':'用戶資訊',
    'TopicDetailScreen':'話題詳情',
    'TopicEditScreen':'話題編輯',
    'ReplyEditScreen':'話題回復',
    'ReplyScreen':'評論回復',
    'ShopDetailScreen':'店鋪詳情',
    'ForumScreen':'社區論壇',
    'GoodsDetailScreen':'商品詳情',
    'PromotionDetailScreen':'促銷活動',
    'CouponDetailScreen':'優惠券詳情',
    'CouponScreen':'我的優惠券',
    'DeviceScreen':'室內機清單',
    'PhotoScreen':'我的相框',

    'Q0':'關於我們',
    'Q0_A':'深圳市結點科技有限公司聚焦智慧社區，致力於創造智慧社區生活。公司運營的智慧社區項目是全生態全平臺智慧社區整體解決方案。其頂層設計基於移動互聯網、物聯網和大數據三大核心技術，是中國唯一能把智慧安防硬體、智慧物業管理、智慧社區全媒體廣告、智慧社區生活服務平臺和超級智慧管家等多個開放平臺連接起來的系統。我們以創造更安全、更方便的生活方式為願景，在國內首家通過移動互聯科技與智慧硬體相結合的模式。提供新一代智慧車輛管理、智能門禁管理、智慧訪客管理、智慧可視對講管理、智慧電梯控制等硬體設備和基於移動互聯網的物業系統實行無縫對接，為社區居民及物業提供全新的智慧社區體驗。',
    'Q1':'如何修改APP的語言？',
    'Q1_A':'我們的APP支持國際化操作，您只需要在手機的設定中，修改當前的國家及語言，重啓APP後即可'
  }
}

/**
 * 对i18进行封装，对界面元素进行国际化翻译
 */
export default function trans(key){
  return I18n.t(key);
}
